import { Metadata } from "next"
import Navigation from "../components/navigation"

export const metadata: Metadata = {
  title: {
    template: "%s | learning Next",
    default: "Loading..."
  },
  description: 'Generated by Next.js'
  /*페이지나 레이아웃만 메타데이터를 내보낼수있고, 
    메타데이터는 레이아웃처럼 중첩이 되지만, 교체가 아닌 병합이 이루워진다.
    즉, 페이지별로 메타데이터를 따로 작성할 필요없이 메타데이터를 추가하고싶은 페이지에서는 추가할 부분만 내보내면되며,
    심지어 메타데이터도 탬플릿화가 가능함.
  */
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><Navigation />{children}</body>
    </html>
  )
}
