import { Metadata } from "next";
import Navigation from "../components/navigation";
import "../styles/global.css";
import style from "../styles/rootlayout.module.css";
import TitleHeader from "../components/header";
import Sidebar from "../components/sidebar";

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Loading..."
  },
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={style.layout}>
          <TitleHeader/>
          <Navigation/>
          <main className={style.body}>
            {children}
          </main>
          <Sidebar/>
        </div>
      </body>
    </html>
  )
}
